spring:
  main:
    show-banner: false
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/isucon2?characterEncoding=UTF-8&amp;socketTimeout=15000&amp;connectTimeout=15000
    username: root
    password: password